# This docking config file provides the mock docker a series of known paths which
# the cleaner robot will follow during a docking (aka cleaning) process. 
#   Example:  Destination: "CLEANZONE" ;  The path here is the trajactory 
#             which starts from "CLEANZONE_start" to "CLEANZONE"
# Note: These waypoints are in (x meters, y meters, yaw radian) form

cleanerBotA:
  clean_lobby: 
    level_name: "L1"
    path: [ [24.24, -38.77, 0.0],
            [18.28, -38.62, 0.0],
            [15.68, -35.3, 0.0],
            [22.73, -35.42, 0.0] ]
  clean_waiting_area:
    level_name: "L1"
    path: [ [8.4, -24.7, 0.0],
            [14.0, -24.7, 0.0],
            [14.0, -23.35, 0.0] ]
  clean_restaurant:
    level_name: "L1"
    path: [ [17.08, -11.32, 0.0],
            [17.2, -7.7, 0.0],
            [11.34, -7.7, 0.0],
            [11.34, -11.3, 0.0] ]
